### ISSUE TITLE
Judges' feedback

### ISSUE THREAD

**Issue by ghost** [jmorc/railschallenge-city-watch#1]
Placeholder issue for judges' feedback.

**Comment by ghost** [comment]
Verified score of `114 points` on the automated scoring, based on the current master branch.

**Comment by ghost** [comment]
Models and DB:
- Can you explain why you have [both of these columns](https://github.com/jmorc/city-watch/blob/master/db/schema.rb#L34-L35)? You only need one foreign key, and the other just duplicates data that already exists on the `Emergency` model.

Dispatching:
- Do you really need [this line](https://github.com/jmorc/city-watch/blob/master/app/models/emergency.rb#L20) if you're also handling that case [here](https://github.com/jmorc/city-watch/blob/master/app/models/emergency.rb#L26)? I haven't looked too deeply at this, but it looks like duplicate code. It won't hurt to just iterate through all the types if they're all `0`.
- Beware of [silent failures](https://github.com/jmorc/city-watch/blob/master/app/models/emergency.rb#L22). When you can, prefer `save!` so that if something goes wrong you throw an exception and alarms are raised. By using `save` here you're taking the chance that a bug will be introduced into your dispatching code, making the model invalid, and you won't know right away because the `save` method fails silently.
- The [top of your dispatch logic](https://github.com/jmorc/city-watch/blob/master/app/models/emergency.rb#L25-L31) can be simplified. The API specification only really requires that you handle the following cases:
  1. When severity is `0`
  2. When severity is high enough that you send all available responders of a given type
  3. When you're able to send just the responders necessary to handle the emergency
- So, that's only three scenarios, yet your `dispatch` method has 5 conditions under which it calls different code. Updating the code around those three scenarios **only** should simplify the rest of the dispatching code in this model.

Routing and controllers:
- Very simple routing. Good.
- [This](https://github.com/jmorc/city-watch/blob/master/app/controllers/emergencies_controller.rb#L29) is a bit of a code smell. You can handle this kind of stuff in another way by using some of the other features of `strong_parameters`. One way might be to put this kind of stuff in your `ApplicationController`:

<pre>
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ActionController::Parameters.action_on_unpermitted_parameters = :raise
  rescue_from ActionController::RoutingError, with: :no_route
  rescue_from ActionController::ParameterMissing, with: :missing_params
  rescue_from ActionController::UnpermittedParameters, with: :unpermitted_params
  ...
end
</pre>

What this does is let you raise an exception when these things happen, and call a single method per exception type to handle the situation. Makes for less exceptional situation handling in the controller actions themselves.
- Similar notes on `RespondersController`. Look into your exception handling code, and make better use of the features of `strong_parameters`. When you make those changes [stuff like this](https://github.com/jmorc/city-watch/blob/master/app/controllers/responders_controller.rb#L77-L88) shouldn't be necessary, and will cease to clutter up your controllers.

**Comment by jmorc** [comment]
Thank you!  Great feedback.
